services:
  postgres:
    image: postgres:latest
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_pgdata:/var/lib/postgresql

volumes:
  postgres_pgdata:
